executable              = job_subgraph.sh
arguments               = $(ClusterId)$(ProcId)
output                  = $(ClusterId).$(ProcId).out
error                   = $(ClusterId).$(ProcId).err
log                     = $(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = job_subgraph.sh, subgraph-contraction
when_to_transfer_output = ON_EXIT
requirements = regexp("A100", TARGET.CUDADeviceName)
request_GPUs = 1
request_CPUs = 12
+JobFlavour = "nextweek"
queue 1
